sudo: required
services:
  - docker

before_install:
  - docker build -t emoscoso/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run emoscoso/react-test npm test --  --coverage
after_success:
  - docker build -t emoscoso/multi-client ./client
  - docker build -t emoscoso/multi-nginx  ./nginx
  - docker build -t emoscoso/multi-server ./server
  - docker build -t emoscoso/multi-worker ./worker
#toma las imagenes y las sube a docker hub
#para ello hay que loguearse en docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push emoscoso/multi-client
  - docker push emoscoso/multi-nginx
  - docker push emoscoso/multi-server
  - docker push emoscoso/multi-worker

deploy:
  provider: elasticbeanstalk #use it set of instruction for deploy
  region: "us-west-2" #region of aws
  app: "multi-docker" #name
  env: "MultiDocker-env-1" #name
  bucket_name: "elasticbeanstalk-us-west-2-336142811313"
  bucket_path: "docker-multi"
  on:
    branch: master #just deploy from master branch
  access_key_id: "$AWS_KEY"
  secret_access_key:
      secure: "$AWS_SECRET" #AWS Access IAM